### ISSUE TITLE
Redis session - using

### ISSUE THREAD

**Issue by jackpoll** [gnieh/spray-session#2]
Hi,

I would like to use this library for a redis session.

A. Is it published in sbt yet? do you plan to publish it?

B. Meanwhile  I've imported it but still didn't know how could I use it, there are errors when trying to.

**Comment by satabin** [comment]
Hi,
for the moment, it is still in development, however I just published the current state as a snapshot version.
If you have sonatype snapshot repository enabled, you can use it with

``` scala
libraryDependencies += "org.gnieh" %% "spray-session" % "0.1.0-SNAPSHOT"
```

You will also need to add the scala redis library dependency in your project as it is marked as provided in spray-session.

As for the errors, what kind of errors do you encounter?
